name: LPDiscordLogger
version: '1.0-SNAPSHOT'
main: com.petalcat.logger.LPDiscordLogger
api-version: '1.21'

commands:
  lpdiscordreload:
    description: Reloads the LPDiscordLogger configuration.
    usage: /<command>
